"""CPPTRAJ execution, shared reference preparation, provenance, and replica splitting."""
from __future__ import annotations

import copy
import hashlib
import json
import math
import re
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

from . import __version__
from .analysis import build_batches, build_pooled_batches, enabled_analyses
from .config import quote, resolve_selections, save_config
from .progress import CalculationProgress, batch_bar


class RunError(RuntimeError):
    pass


def utc_now():
    return datetime.now(timezone.utc).isoformat()


def executable(config):
    binary = config["cpptraj"]
    path = shutil.which(binary)
    if path:
        return path
    if Path(binary).is_file():
        return str(Path(binary).resolve())
    raise RunError("CPPTRAJ was not found. Activate your AmberTools environment, or set cpptraj to its executable path in the configuration. On Windows, run the workflow and CPPTRAJ together inside WSL/Linux if using a Linux installation.")


def invoke(binary, args, cwd, log_path):
    """No shell interpolation; logs persist even on failure."""
    log_path = Path(log_path)
    log_path.parent.mkdir(parents=True, exist_ok=True)
    with log_path.open("w", encoding="utf-8") as log:
        try:
            result = subprocess.run([binary, *args], cwd=cwd, stdout=log, stderr=subprocess.STDOUT, text=True, check=False)
        except OSError as exc:
            raise RunError(f"Could not execute CPPTRAJ: {exc}") from exc
    text = log_path.read_text(encoding="utf-8", errors="replace")
    errors = re.findall(r"(?im)^\s*(?:Error:|Fatal:).*$", text)
    if result.returncode != 0 or errors:
        raise RunError(f"CPPTRAJ failed (exit {result.returncode}); see {log_path}. " + " ".join(errors[:3]))
    return text


def write_script(path, commands):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("# Generated by CPPTRAJ Workbench; exact commands retained for reproducibility.\n" + "\n".join(commands) + "\n", encoding="utf-8")


def execute_script(binary, commands, directory, stem, *, show_progress=True):
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / f"{stem}.in"
    write_script(path, commands)
    with CalculationProgress(directory / f"{stem}.log", enabled=show_progress):
        return invoke(binary, ["-i", str(path)], directory, directory / f"{stem}.log")


def image_commands(config):
    if config["imaging"]["mode"] == "off":
        return []
    anchor = config["imaging"].get("anchor")
    return ["autoimage" + (" anchor " + quote(anchor) if anchor else "")]


def select_windows(lengths, frames):
    """Select frames over the joined segments of ONE replica, preserving stride."""
    start, stop, stride = frames["start"], frames["stop"], frames["stride"]
    total = sum(lengths)
    if start > total:
        raise RunError(f"Selection starts at {start}, but replica has only {total} frames.")
    if stop == -1:
        stop = total
    elif stop > total:
        raise RunError(f"Selection stops at {stop}, but replica has only {total} frames. Use -1 for all remaining frames.")
    offset = 0
    windows = []
    for length in lengths:
        low, high = max(start, offset + 1), min(stop, offset + length)
        first = low + (start - low) % stride
        if first <= high:
            last = first + ((high - first) // stride) * stride
            windows.append({"start": first - offset, "stop": last - offset, "stride": stride,
                            "offset": offset, "count": (last - first) // stride + 1})
        else:
            windows.append(None)
        offset += length
    return windows


def trajin_commands(replica):
    return [f"trajin {quote(path)} {window['start']} {window['stop']} {window['stride']}"
            for path, window in zip(replica["trajectories"], replica["windows"]) if window]


def _fingerprint(path, hash_file=False):
    path = Path(path)
    stat = path.stat()
    result = {"path": str(path), "size_bytes": stat.st_size, "mtime_ns": stat.st_mtime_ns}
    if hash_file:
        digest = hashlib.sha256()
        with path.open("rb") as handle:
            for block in iter(lambda: handle.read(1024 * 1024), b""):
                digest.update(block)
        result["sha256"] = digest.hexdigest()
    return result


def _prepare(config, output, require_empty=True):
    output = Path(output)
    if require_empty and output.exists() and any(output.iterdir()):
        raise RunError(f"Results directory is not empty: {output}. Choose a new --output to avoid mixing or overwriting runs.")
    selections, info = resolve_selections(config)
    batches = build_batches(config, selections)
    pooled = build_pooled_batches(config, selections)
    if not batches and not pooled:
        raise RunError("No applicable analyses selected. Check selections and analysis.enabled.")
    output.mkdir(parents=True, exist_ok=True)
    save_config(config, output / "resolved_config.json")
    save_config(info, output / "topology_inspection.json")
    with (output / "residue_map.dat").open("w", encoding="utf-8") as handle:
        handle.write("#topology_residue\tname\tclassification\tatoms\n")
        for residue in info["residues"]:
            handle.write(f"{residue['index']}\t{residue['name']}\t{residue['kind']}\t{','.join(residue['atoms'])}\n")
    plan = {"per_replica": batches, "pooled": pooled, "selections": selections,
            "replicas": config["replicas"], "warnings": info["warnings"]}
    save_config(plan, output / "plan.json")
    return selections, info, batches, pooled


def make_plan(config, output=None):
    config = copy.deepcopy(config)
    directory = Path(output or config["output"])
    selections, info, batches, pooled = _prepare(config, directory)
    lines = ["# CPPTRAJ analysis plan", "", "This is an offline plan. `run` verifies atom masks and trajectory lengths with CPPTRAJ and writes executable input scripts with resolved frame ranges.", "",
             f"Topology: `{config['topology']}`", f"Global fit: `{config['fit_mask']}`", f"Imaging: {config['imaging']['mode']}",
             "", "Frame start/stop/stride apply to the joined segments of each replica. A common imaged reference is used for every replica.", ""]
    for rep in config["replicas"]:
        lines += [f"## {rep['name']}", ""] + [f"{i}. `{path}`" for i, path in enumerate(rep["trajectories"], 1)] + [""]
    for label, jobs in (("Per-replica analyses", batches), ("Shared pooled analyses", pooled)):
        lines += [f"## {label}", ""]
        for batch in jobs:
            lines += [f"### {batch['name']}", "", batch["description"], "", "```text", *batch["commands"], "run", *batch.get("post_commands", []), "```", ""]
    lines += ["## Checks before running", "", "- One matching topology and atom order across all replicas.", "- Review replica versus segment grouping and segment order.", "- Review residue numbering, imaging anchor, and global fit selection.", "- Time is a user-specified saved-frame interval; otherwise axes use analyzed frames.", "- Advanced analyses have configurable atom, frame, and estimated memory limits.", ""]
    lines += [f"- {warning}" for warning in info["warnings"]]
    (directory / "PLAN.md").write_text("\n".join(lines), encoding="utf-8")
    return directory


def preflight(binary, config, selections, batches, pooled, directory):
    directory.mkdir(parents=True, exist_ok=True)
    masks = {config["fit_mask"], *[s["mask"] for s in config["sections"]]}
    if config.get("structure_view", {}).get("enabled", True) and selections.get("heavy"):
        masks.add(selections["heavy"])
    for monitor in config.get("monitors", []):
        masks.update(monitor["masks"])
    for item in config.get("solvation", []):
        masks.update((item["mask1"], item["mask2"]))
    for pair in config["interactions"]:
        masks.update([pair["mask1"], pair["mask2"]])
    if config["imaging"].get("anchor"):
        masks.add(config["imaging"]["anchor"])
    for batch in batches + pooled:
        if batch.get("coordinate_mask"):
            masks.add(batch["coordinate_mask"])
    # Validate chemistry selections actually used by automatic actions too.
    for name in ("protein", "nucleic", "solute"):
        if name in selections:
            masks.add(selections[name])
    selected = {}
    for i, mask in enumerate(sorted(masks), 1):
        log = invoke(binary, ["-p", config["topology"], "-ms", mask], directory, directory / f"mask_{i:03}.log")
        matches = re.findall(r"(?m)^\s*Selected\s*=\s*([^\r\n]*)", log)
        if not matches:
            raise RunError(f"Unable to parse CPPTRAJ -ms output for {mask}; inspect mask_{i:03}.log.")
        atoms = [int(x) for x in matches[-1].split() if x.isdigit()]
        if not atoms:
            raise RunError(f"Mask selects zero atoms: {mask}")
        selected[mask] = atoms
    if len(selected[config["fit_mask"]]) < 3:
        raise RunError("Global RMS fitting needs at least three atoms; choose a noncollinear fit mask.")
    for monitor in config.get("monitors", []):
        groups = [set(selected[mask]) for mask in monitor["masks"]]
        if any(groups[i] == groups[j] for i in range(len(groups)) for j in range(i)):
            raise RunError(f"Monitor {monitor['name']} has identical point selections; choose distinct atoms/groups.")
    for interface in config["interactions"]:
        if set(selected[interface["mask1"]]) & set(selected[interface["mask2"]]):
            raise RunError(f"Interaction masks overlap for {interface['name']}; use disjoint selections.")
    for item in config.get("solvation", []):
        if set(selected[item["mask1"]]) & set(selected[item["mask2"]]):
            raise RunError(f"Solvation selections overlap for {item['name']}; this workflow requires disjoint selections.")
    for i, batch in enumerate(batches, 1):
        if batch.get("contact_masks"):
            mask = "|".join(f"({m})" for m in batch["contact_masks"])
            log = invoke(binary, ["-p", config["topology"], "-mr", mask], directory, directory / f"contact_residues_{i:03}.log")
            matches = re.findall(r"(?m)^\s*Selected\s*=\s*([^\r\n]*)", log)
            residues = [int(x) for x in matches[-1].split() if x.isdigit()] if matches else []
            if not residues:
                raise RunError(f"Could not determine contact-map residue span for {batch['name']}.")
            span = max(residues) - min(residues) + 1
            if span > config["advanced"]["max_matrix_atoms"]:
                raise RunError(f"{batch['name']}: contact-map residue span {span} exceeds max_matrix_atoms={config['advanced']['max_matrix_atoms']}. Narrow interface masks or disable contacts; CPPTRAJ allocates across the full residue span.")
    replicas = copy.deepcopy(config["replicas"])
    for replica in replicas:
        lengths = []
        for index, path in enumerate(replica["trajectories"], 1):
            log = invoke(binary, ["-p", config["topology"], "-y", path, "-tl"], directory, directory / f"length_{replica['name']}_{index:04}.log")
            matches = re.findall(r"(?m)^\s*Frames:\s*(\d+)\s*$", log)
            if not matches or int(matches[-1]) < 1:
                raise RunError(f"Could not determine frame count for {path}. This workflow requires a CPPTRAJ reader that reports trajectory length.")
            lengths.append(int(matches[-1]))
        replica["lengths"] = lengths
        replica["windows"] = select_windows(lengths, config["frames"])
        replica["frame_count"] = sum(w["count"] for w in replica["windows"] if w)
    return selected, replicas


def resource_check(config, batch, atoms, frame_count):
    """Conservative pre-allocation estimate; not a promise about native peak RAM."""
    if not batch.get("coordinate_mask"):
        return
    limits = config["advanced"]
    if "pca" in batch["name"] and (frame_count <= limits["pca_modes"] or 3 * atoms < limits["pca_modes"]):
        raise RunError("PCA requires more frames than requested modes, and at least as many Cartesian coordinates as modes.")
    if "cluster" in batch["name"] and math.ceil(frame_count / limits["cluster_sieve"]) < limits["cluster_count"]:
        raise RunError("Too few sieved frames for cluster_count. Reduce cluster_sieve or cluster_count.")
    if atoms > limits["max_matrix_atoms"]:
        raise RunError(f"{batch['name']}: {atoms} atoms exceeds max_matrix_atoms={limits['max_matrix_atoms']}. Narrow matrix_mask.")
    if batch.get("pooled") or batch.get("resource_class") == "pairwise":
        if frame_count > limits["max_frames"]:
            raise RunError(f"{batch['name']}: {frame_count} frames exceeds max_frames={limits['max_frames']}. Increase frames.stride or explicitly raise the limit.")
    # Includes a coordinate buffer and several dense double-precision matrices.
    if batch.get("resource_class") == "atom_matrix":
        # DCCM accumulates moments while streaming; it does not retain frames.
        estimate = 8 * (4 * atoms * atoms + 12 * atoms)
    else:
        estimate = 8 * (3 * atoms * frame_count + 4 * (3 * atoms) ** 2)
    if "pairwise" in batch["name"] or "cluster" in batch["name"]:
        n = frame_count if "pairwise" in batch["name"] else math.ceil(frame_count / limits["cluster_sieve"])
        estimate += 16 * n * n
    gb = estimate / 1024 ** 3
    if gb > limits["max_memory_gb"]:
        raise RunError(f"{batch['name']}: conservative memory estimate {gb:.2f} GiB exceeds max_memory_gb={limits['max_memory_gb']}. Narrow masks, increase stride/sieve, or raise the explicit limit.")


def _artifact_paths(batch, directory, selected):
    artifacts = copy.deepcopy(batch["artifacts"])
    for artifact in artifacts:
        artifact["path"] = str(directory / artifact["path"])
        if artifact["kind"] == "matrix" and batch.get("coordinate_mask") and artifact["analysis"] in {"dccm", "correlation"}:
            metadata = artifact.setdefault("metadata", {})
            metadata["atom_ids"] = selected[batch["coordinate_mask"]]
            metadata.update(matrix_type="correlation", x_unit="topology atom index", y_unit="topology atom index")
            metadata["x_labels"] = metadata["atom_ids"]
            metadata["y_labels"] = metadata["atom_ids"]
        elif artifact["analysis"] == "pca_covariance":
            artifact.setdefault("metadata", {}).update(matrix_type="covariance", x_unit="selected Cartesian coordinate", y_unit="selected Cartesian coordinate")
        elif artifact["analysis"] == "pairwise_rmsd":
            artifact.setdefault("metadata", {}).update(matrix_type="distance", x_unit="pooled analyzed frame", y_unit="pooled analyzed frame")
    return artifacts


def _check_artifacts(artifacts):
    missing = [a["path"] for a in artifacts if not a.get("metadata", {}).get("optional") and (not Path(a["path"]).is_file() or Path(a["path"]).stat().st_size == 0)]
    if missing:
        raise RunError("CPPTRAJ did not produce required output(s): " + ", ".join(missing))


def _frame_map(config, rep, output):
    path = output / "replicas" / rep["name"] / "frame_map.dat"
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        handle.write("#analyzed_frame\tsegment\tsource_frame\tjoined_frame\telapsed_ps\treconstructed_time_ps\n")
        n = 0
        for segment, w in enumerate(rep["windows"], 1):
            if not w:
                continue
            for source in range(w["start"], w["stop"] + 1, w["stride"]):
                n += 1
                elapsed = "nan" if config["frames"]["dt_ps"] is None else f"{(n - 1) * config['frames']['stride'] * config['frames']['dt_ps']:.12g}"
                time = "nan" if config["frames"]["dt_ps"] is None else f"{(source + w['offset'] - 1) * config['frames']['dt_ps']:.12g}"
                handle.write(f"{n}\t{segment}\t{source}\t{source + w['offset']}\t{elapsed}\t{time}\n")


def _split_pooled(batch, artifacts, replicas, output):
    """Partition common-basis frame datasets using verified input frame counts."""
    import numpy as np
    total = sum(r["frame_count"] for r in replicas)
    for artifact in artifacts:
        if artifact["kind"] != "timeseries" or not Path(artifact["path"]).is_file():
            continue
        # Independent parser for CPPTRAJ standard frame data; report parser may
        # return a richer object and should not define the execution contract.
        comments = []
        rows = []
        with Path(artifact["path"]).open(encoding="utf-8") as handle:
            for line in handle:
                if line.lstrip().startswith("#"):
                    comments.append(line.rstrip())
                elif line.strip():
                    rows.append([float(x.replace("D", "E")) for x in line.split()])
        data = np.asarray(rows, dtype=float)
        if data.ndim != 2 or len(data) != total or data.shape[1] < 2 or not np.array_equal(data[:, 0], np.arange(1, total + 1)):
            raise RunError(f"Pooled frame output cannot be safely split: {artifact['path']}")
        start = 0
        for replica in replicas:
            count = replica["frame_count"]
            block = data[start:start + count].copy()
            block[:, 0] = np.arange(1, count + 1)
            directory = output / "replicas" / replica["name"] / batch["name"]
            directory.mkdir(parents=True, exist_ok=True)
            target = directory / Path(artifact["path"]).name
            np.savetxt(target, block, fmt="%.12g", header="\n".join(comments).lstrip("# "), comments="# ")
            split = copy.deepcopy(artifact)
            split["path"] = str(target)
            split.setdefault("metadata", {})["shared_basis"] = True
            replica["artifacts"].append(split)
            start += count


def run_workflow(config, *, make_plots=True, progress=print):
    from .console import event, panel
    if progress is print:
        progress = event
        panel("CPPTRAJ WORKBENCH · RUN", [("Study", config.get("study", {}).get("title", "MD analysis")),
              ("Replicas", len(config["replicas"])), ("Trajectory chunks", sum(len(r["trajectories"]) for r in config["replicas"])),
              ("Analyses", ", ".join(config["analysis"]["enabled"]) if config["analysis"].get("enabled") is not None else config["analysis"]["level"]), ("Extra analyses", ", ".join(config["analysis"].get("additional", [])) or "None"),
              ("Frames", config["frames"]), ("Output", config["output"])])
    # Fail before long trajectory processing if numerical reporting is unavailable.
    try:
        import numpy  # noqa: F401
    except ImportError as exc:
        raise RunError("NumPy is required for reporting. Use an existing Python environment with the dependencies in requirements.txt.") from exc
    config = copy.deepcopy(config)
    binary = executable(config)
    output = Path(config["output"])
    selections, info, batches, pooled = _prepare(config, output)
    manifest = {"workbench_version": __version__, "started": utc_now(), "status": "running", "replicas": [], "pooled": [], "warnings": info["warnings"], "inputs": []}
    from .community import environment_info, write_methods
    manifest["environment"] = environment_info(config.get("cpptraj", "cpptraj"))
    manifest_path = output / "manifest.json"
    def save():
        save_config(manifest, manifest_path)
    save()
    try:
        manifest["cpptraj_version"] = invoke(binary, ["--version"], output, output / "cpptraj_version.log").strip()
        manifest["inputs"] = [_fingerprint(config["topology"], True)] + [_fingerprint(p) for r in config["replicas"] for p in r["trajectories"]]
        if config["reference"]:
            manifest["inputs"].append(_fingerprint(config["reference"], True))
        progress("Validating selections and counting trajectory frames...")
        selected, replicas = preflight(binary, config, selections, batches, pooled, output / "preflight")
        save_config(selected, output / "selected_atoms.json")
        for replica in replicas:
            replica.update(status="pending", artifacts=[], batches=[])
            _frame_map(config, replica, output)
        manifest["replicas"] = replicas
        save()
        total = sum(r["frame_count"] for r in replicas)
        for batch in batches + pooled:
            if batch.get("coordinate_mask"):
                resource_check(config, batch, len(selected[batch["coordinate_mask"]]), total if batch.get("pooled") else max(r["frame_count"] for r in replicas))
        if config["reference"]:
            ref_trajin = f"trajin {quote(config['reference'])} 1 1"
        else:
            first_rep = replicas[0]
            i = next(i for i, w in enumerate(first_rep["windows"]) if w)
            w = first_rep["windows"][i]
            ref_trajin = f"trajin {quote(first_rep['trajectories'][i])} {w['start']} {w['start']}"
        reference = output / "reference" / "common.rst7"
        show_progress = config.get("progress", {}).get("enabled", True)
        jobs_total = len(replicas) * len(batches) + len(pooled)
        jobs_done = jobs_failed = 0
        progress("Preparing a common imaged reference...")
        execute_script(binary, [f"parm {quote(config['topology'])}", ref_trajin, *image_commands(config),
                               "trajout common.rst7 restart", "run", "quit"], reference.parent, "prepare_reference", show_progress=show_progress)
        if not reference.is_file():
            raise RunError(f"Common reference was not generated: {reference}")
        view_options = config.get("structure_view", {})
        view_mask = selections.get("heavy")
        manifest["structure_view"] = {"status": "unavailable", "message": "No automatic heavy-solute selection is available."}
        if not view_options.get("enabled", True):
            manifest["structure_view"] = {"status": "disabled", "message": "Disabled in configuration."}
        elif view_mask and len(selected.get(view_mask, [])) > view_options.get("max_atoms", 12000):
            manifest["structure_view"] = {"status": "atom_limit", "message": "Heavy solute exceeds the structure-preview atom limit; no export was attempted."}
        elif view_mask:
            try:
                progress("Exporting one compact reference structure for the offline report...")
                execute_script(binary, [f"parm {quote(config['topology'])}", f"trajin {quote(reference)} 1 1",
                               f"strip {quote('!(' + view_mask + ')')}", "trajout viewer.pdb pdb nobox", "run", "quit"],
                               reference.parent, "viewer_export", show_progress=False)
                manifest["structure_view"] = {"status": "complete", "selection": view_mask, "source": "reference/viewer.pdb"}
            except RunError as exc:
                manifest["structure_view"] = {"status": "unavailable", "message": f"Optional reference export failed: {exc}"}
                progress("Optional structure preview unavailable; numerical analyses will continue.")
        save()
        def header(reps, preserve_box=False):
            return [f"parm {quote(config['topology'])}", *[line for rep in reps for line in trajin_commands(rep)],
                    f"reference {quote(reference)} [COMMON]", *image_commands(config),
                    f"rms GLOBAL ref [COMMON] {quote(config['fit_mask'])} {'nomod' if preserve_box else ''} out alignment_check.dat"]
        for replica in replicas:
            for batch in batches:
                progress(f"{replica['name']}: {batch['name']} ({replica['frame_count']} selected frames)")
                directory = output / "replicas" / replica["name"] / batch["name"]
                record = {"name": batch["name"], "status": "running"}
                replica["batches"].append(record)
                save()
                try:
                    execute_script(binary, [*header([replica], batch.get('preserve_box', False)), *batch["commands"], "run", *batch.get("post_commands", []), "quit"], directory, "cpptraj", show_progress=show_progress)
                    artifacts = _artifact_paths(batch, directory, selected)
                    _check_artifacts(artifacts)
                    # Every action run must have processed precisely the planned frames.
                    alignment_path = directory / "alignment_check.dat"
                    if not alignment_path.is_file():
                        raise RunError(f"Alignment/frame-count output missing: {alignment_path}")
                    count = sum(1 for line in alignment_path.read_text().splitlines() if line.strip() and not line.lstrip().startswith("#"))
                    if count != replica["frame_count"]:
                        raise RunError(f"Unexpected processed frame count: {count}, expected {replica['frame_count']}")
                    replica["artifacts"].extend(artifacts)
                    record["status"] = "complete"
                except RunError as exc:
                    record.update(status="failed", error=str(exc))
                    progress(f"  Failed: {exc}")
                jobs_done += 1
                jobs_failed += record["status"] == "failed"
                if show_progress:
                    progress(batch_bar(jobs_done, jobs_total, jobs_failed))
                save()
            replica["status"] = "complete" if all(b["status"] == "complete" for b in replica["batches"]) else "partial"
        for batch in pooled:
            progress(f"Shared pooled analysis: {batch['name']} ({total} frames)")
            directory = output / "pooled" / batch["name"]
            record = {"name": batch["name"], "status": "running", "artifacts": []}
            manifest["pooled"].append(record)
            save()
            try:
                execute_script(binary, [*header(replicas), *batch["commands"], "run", *batch.get("post_commands", []), "quit"], directory, "cpptraj", show_progress=show_progress)
                artifacts = _artifact_paths(batch, directory, selected)
                _check_artifacts(artifacts)
                _split_pooled(batch, artifacts, replicas, output)
                record.update(status="complete", artifacts=artifacts)
            except (RunError, ValueError, ImportError) as exc:
                record.update(status="failed", error=str(exc))
                progress(f"  Failed: {exc}")
            jobs_done += 1
            jobs_failed += record["status"] == "failed"
            if show_progress:
                progress(batch_bar(jobs_done, jobs_total, jobs_failed))
            save()
        failures = any(r["status"] != "complete" for r in replicas) or any(p["status"] != "complete" for p in manifest["pooled"])
        manifest["status"] = "partial" if failures else "complete"
        manifest["finished"] = utc_now()
        save()
        from .reporting import report_results
        report_config = copy.deepcopy(config)
        if not make_plots:
            report_config["plots"]["enabled"] = False
        progress("Combining replicas and generating statistical reports...")
        write_methods(config, manifest, output)
        manifest["report"] = report_results(report_config, manifest, output)
        if manifest["report"].get("status") != "complete":
            manifest["status"] = "partial"
        save()
        write_methods(config, manifest, output)
        from .dashboard import write_dashboard
        write_dashboard(report_config, manifest, manifest["report"], output)
        return manifest
    except KeyboardInterrupt:
        manifest.update(status="interrupted", finished=utc_now())
        save()
        try:
            write_methods(config, manifest, output)
        except OSError:
            pass  # Preserve the original interruption if output storage is unavailable.
        raise
    except Exception as exc:
        manifest.update(status="failed", error=str(exc), finished=utc_now())
        save()
        try:
            write_methods(config, manifest, output)
        except OSError:
            pass  # Preserve the original error if output storage is unavailable.
        raise


def replot(output, *, make_plots=True):
    from .reporting import report_results
    from .community import rebase_manifest
    directory = Path(output).expanduser().resolve()
    config = json.loads((directory / "resolved_config.json").read_text(encoding="utf-8"))
    manifest = json.loads((directory / "manifest.json").read_text(encoding="utf-8"))
    manifest = rebase_manifest(manifest, config["output"], directory)
    config["output"] = str(directory)
    config.setdefault("plots", {})["enabled"] = make_plots and config.get("plots", {}).get("enabled", True)
    # Retain the original run environment; report regeneration has its own record.
    from .community import environment_info
    save_config(environment_info(config.get("cpptraj", "cpptraj")), directory / "report_environment.json")
    return report_results(config, manifest, directory)
