"""One-sentence explanations shown before setup questions."""

HELP = [
    ("topology", "Choose the topology with exactly the same atoms and atom order as every trajectory in this comparison."),
    ("choose trajectories", "Select saved trajectory files in chronological order within each simulation."),
    ("grouped", "Group sequential chunks together and keep independently started simulations as separate replicas."),
    ("grouping and", "Confirm the grouping because combining independent simulations as one continuous trajectory changes the analysis."),
    ("trajectory indices", "These file numbers define the chronological chunks of this replica."),
    ("replica name", "Use a short unique label that colleagues will recognize in tables and figure legends."),
    ("study title", "This title appears at the top of the shareable HTML report."),
    ("suggested sections", "Suggested sections cover detected biomolecular regions and can be replaced with regions relevant to your question."),
    ("custom section", "A section is a named residue or atom selection that will receive its own analyses."),
    ("section name", "Give this region a unique label such as domainA or binding_site."),
    ("global alignment", "Fit a stable core to remove overall motion while retaining relative movements of other domains."),
    ("reference structure", "Auto uses replica 1's first selected frame as the common reference for all replicas."),
    ("imaging: auto", "Auto follows known topology periodicity, on reconstructs periodic molecules, and off keeps the supplied coordinates."),
    ("imaging anchor", "The anchor is the molecule or region around which a periodic complex is assembled."),
    ("first frame", "Start after the equilibration interval you have independently chosen to exclude."),
    ("last frame", "Use -1 to include all remaining frames or set an endpoint for a matched production window."),
    ("every nth", "A larger stride reduces processing but can miss rapid transitions and short-lived events."),
    ("saved-frame interval", "Enter the time between saved frames before analysis striding, or zero to retain frame-number axes."),
    ("analysis level", "Basic covers structure, Standard adds routine interactions, and Advanced adds specialist and more expensive analyses."),
    ("additional analyses", "Add only the measurements needed for your question, including custom geometry monitors."),
    ("enter numbers", "Choose multiple numbered analyses using commas or ranges; zero leaves the preset unchanged."),
    ("geometry entry", "Guided atoms avoids mask syntax, named groups uses region centers, and quick entry accepts all ordered selections on one line."),
    ("monitor name", "Use a descriptive label such as gate_distance so the measurement is easy to find in the report."),
    ("residue number", "Use the topology's one-based residue index, which may differ from the numbering in your original PDB."),
    ("atom name", "Choose the exact atom name listed for this residue rather than a wildcard selection."),
    ("choose group", "Select a named region to monitor its center, or enter an explicit residue/atom selection."),
    ("ordered selections", "Separate the two, three or four ordered selections with semicolons, using forms such as 25:CA or :1-20."),
    ("keep this monitor", "Check the ordered points because reversing or moving them changes the measured geometry."),
    ("mass or geometry", "Mass centers weight atoms by their masses, while geometry centers weight every selected atom equally."),
    ("minimum-image", "Minimum-image distance measures the nearest periodic separation and requires a trajectory box."),
    ("raw angles", "Both ranges describe the same torsion; the reporting code uses circular statistics across the wrap boundary."),
    ("another", "Add another independently named measurement or continue with the remaining setup."),
    ("solvation analysis name", "Choose a unique label for this pair of solute and surrounding-particle selections."),
    ("customize figure", "Keep the publication defaults or choose your journal's font, canvas size and SVG text requirements."),
    ("nastruct residue", "Restrict nucleic-structure calculations to a topology residue range or keep all detected nucleic residues."),
    ("modified nucleic", "Map a modified residue only when its atom names and geometry support the intended canonical base."),
    ("modified residue name", "Enter the modified base's exact residue label from the topology."),
    ("canonical base", "Choose the canonical base whose atom correspondence matches the modified residue."),
    ("explicit interface", "Define two regions when you want distances, contacts or hydrogen bonds specifically between them."),
    ("interface name", "Use a unique label for the pair of interacting regions."),
    ("contact cutoff", "This distance in angstroms defines a geometric contact and should match your scientific convention."),
    ("advanced coordinate", "A compact representative atom set makes covariance and clustering calculations more manageable."),
    ("principal components", "Retain enough common-basis modes to inspect important motions without assuming the first modes capture all sampling."),
    ("cluster count", "Choose an exploratory number of structural groups and inspect how results depend on that choice."),
    ("clustering sieve", "Fit clusters to a random 1/N subset and assign the remaining frames. This reduces clustering cost without changing sampling for other analyses."),
    ("block size", "Choose contiguous blocks longer than the observable correlation scale before interpreting block variability."),
    ("cpptraj executable", "Use cpptraj from your active environment or supply its full path in the same operating system."),
    ("results directory", "Choose a new empty folder separate from the original simulation inputs."),
    ("run cpptraj now", "Yes starts the calculations immediately; no keeps the saved configuration for a later cluster job."),
    ("mask", "Use a named selection or topology residue/atom expression such as backbone, :1-20 or :25@CA."),
    ("named selection", "Select a predefined region or enter a CPPTRAJ expression using topology residue numbers."),
]


def explanation(prompt):
    lower = prompt.lower()
    return next((text for pattern, text in HELP if pattern in lower),
                "Enter the requested value or press Enter to accept the displayed default.")
